import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Main from "../components/Main";
import MobileNavigation from "../components/Navigation/MobileNavigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>VenusLab</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <MobileNavigation />

      <Main />

      <Footer />
    </>
  );
}
